services:
  pihole-sync:
    image: olivierprotips/ph-sync:latest
    container_name: ph-sync
    environment:
      - PIHOLE_MASTER=http://pihole.master|password123
      - PIHOLE_SLAVES=http://pihole.slave1|password123,http://pihole.slave2|password123
      - CRON_SCHEDULE=0 * * * *
      - TZ=Europe/Paris
    restart: unless-stopped